# This file was generated by the {rix} R package v0.18.1 on 2026-09-24
# with following call:
# >rix(date = "2025-11-24",
#  > r_pkgs = c("roxygen2",
#  > "testthat",
#  > "knitr",
#  > "rmarkdown",
#  > "rvest",
#  > "httr",
#  > "dplyr",
#  > "purrr",
#  > "stringr",
#  > "tibble",
#  > "ggplot2",
#  > "lubridate",
#  > "tidyr",
#  > "scales",
#  > "covr",
#  > "pkgdown",
#  > "targets",
#  > "tarchetypes",
#  > "sf",
#  > "arrow",
#  > "osmdata",
#  > "leaflet",
#  > "jsonlite",
#  > "readr",
#  > "httr2",
#  > "gert",
#  > "gh",
#  > "usethis",
#  > "R.utils",
#  > "rprojroot",
#  > "quarto",
#  > "pkgload",
#  > "rcmdcheck",
#  > "visNetwork",
#  > "gender"),
#  > system_pkgs = NULL,
#  > git_pkgs = list(package_name = "genderdata",
#  > repo_url = "https://github.com/lmullen/genderdata",
#  >      commit = "df16017149a8adb9a75a2dcf734007cab12dd5da"),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > print = TRUE,
#  > r_ver = "4.5.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-11-24.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      arrow
      covr
      dplyr
      gender
      gert
      ggplot2
      gh
      httr
      httr2
      jsonlite
      knitr
      leaflet
      lubridate
      osmdata
      pkgdown
      pkgload
      purrr
      quarto
      R_utils
      rcmdcheck
      readr
      rmarkdown
      roxygen2
      rprojroot
      rvest
      scales
      sf
      stringr
      tarchetypes
      targets
      testthat
      tibble
      tidyr
      usethis
      visNetwork;
  };
 
    genderdata = (pkgs.rPackages.buildRPackage {
      name = "genderdata";
      src = pkgs.fetchgit {
        url = "https://github.com/lmullen/genderdata";
        rev = "df16017149a8adb9a75a2dcf734007cab12dd5da";
        sha256 = "sha256-8DAx6fSFRIEdwReK+h1jDvfjeMxlJNXc65+b1QT9C9U=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) ;
      };
    });
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      R
      quarto
      which
      pandoc;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ genderdata rpkgs system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
