# This file was generated by the {rix} R package v0.17.2 on 2025-11-30
# with following call:
# >rix(date = "2025-11-10",
#  > r_pkgs = c("devtools",
#  > "roxygen2",
#  > "testthat",
#  > "knitr",
#  > "rmarkdown",
#  > "rvest",
#  > "httr",
#  > "dplyr",
#  > "purrr",
#  > "stringr",
#  > "tibble",
#  > "ggplot2",
#  > "lubridate",
#  > "tidyr",
#  > "scales",
#  > "covr",
#  > "pkgdown",
#  > "targets",
#  > "tarchetypes",
#  > "sf",
#  > "arrow",
#  > "WikidataQueryServiceR",
#  > "osmdata",
#  > "leaflet",
#  > "jsonlite",
#  > "httr2",
#  > "gert",
#  > "gh",
#  > "usethis",
#  > "R.utils",
#  > "rprojroot",
#  > "quarto"),
#  > system_pkgs = unique(c("pandoc",
#  > "qpdf")),
#  > git_pkgs = NULL,
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > print = TRUE,
#  >      r_ver = "4.5.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-11-10.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      arrow
      covr
      devtools
      dplyr
      gert
      ggplot2
      gh
      httr
      httr2
      jsonlite
      knitr
      leaflet
      lubridate
      osmdata
      pkgdown
      purrr
      quarto
      R_utils
      rmarkdown
      roxygen2
      rprojroot
      rvest
      scales
      sf
      stringr
      tarchetypes
      targets
      testthat
      tibble
      tidyr
      usethis
      WikidataQueryServiceR;
  };
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      pandoc
      qpdf
      R
      quarto
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
